### ISSUE TITLE
[Feature Request]: Is there any plan to set version 4.0 to support C++11?

### ISSUE THREAD

**Issue by musuoliniao** [rikyoz/bit7z#111]
### Feature description

Cause C++11 is more widely used C_standard, many projects are based on it . Thank you and expect for your reply.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!

> Is there any plan to set version 4.0 to support C++11?
> Cause C++11 is more widely used C_standard, many projects are based on it . 

As far as I know, you should be able to link bit7z to C++11 projects without any issues, provided that you use the same compiler for building both (or even different compiler versions with ABI-compatible standard libraries).

Did you experience any issues with linking bit7z to a C++11 project? If so, could you provide more details (e.g., compiler used, its version, etc.)?
Thank you!

As a side note, I have no plan to reintroduce C++11 support for the internal source code of bit7z v4.0, at least for now.

I moved the project to use at least the C++14 standard since it allowed me to clean up the code and make it more readable and easily maintainable.

However, I don't exclude the possibility of reintroducing the support to C++11 to a later version of the library (v4.1?), but only if it doesn't result in worse code maintainability.

The library's public API should still be C++11-compatible, though (unless there's some error somewhere)!
