### ISSUE TITLE
[Feature Request]: Allow BitArchiveRead to be movable (not deleted)

### ISSUE THREAD

**Issue by mez0ru** [rikyoz/bit7z#131]
### Feature description

I don't know if I should mark this as a bug, but I have a situation where I need to cache multiple BitArchiveRead objects for quicker access, I'm currently building a rest api, but I can't cache the object since it's a "deleted object".
I tried making the move constructor undeleted, iow default. But didn't work out.
Is there any suggestion or a workaround for this issue?

### Additional context

I get this error when I compile my project.
Error C2280 'bit7z::BitArchiveReader &bit7z::BitArchiveReader::operator =(const bit7z::BitArchiveReader &)': attempting to reference a deleted function.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by mez0ru** [comment]
using shared_ptr solved the problem.

**Comment by rikyoz** [comment]
Hi!
I'm sorry for not getting back to you sooner!

> I tried making the move constructor undeleted, iow default. But didn't work out.

> I get this error when I compile my project.
> Error C2280 'bit7z::BitArchiveReader &bit7z::BitArchiveReader::operator =(const bit7z::BitArchiveReader &)': attempting to reference a deleted function.

The problem is that the `BitArchiveReader` class inherits some reference member variables from its base classes.
There are various reasons for it, but this choice ultimately makes the class implicitly not copyable and not movable.
To make this property more evident in the API, I explicitly deleted the copy and move constructors/assignment operators.
This is why it fails to compile even after undeleting the move constructor.

I often thought about simplifying the bit7z API by avoiding reference member variables. This would allow moving bit7z objects and directly storing them in STL containers.
However, it's a challenging task since the use of reference member variables was a choice made in the early stages of the project, and it spread throughout the whole library.
Any change to this might require a breaking change in the API itself.
I will work on these issues in future library versions for sure!

> Is there any suggestion or a workaround for this issue?

> using shared_ptr solved the problem.

Yeah, using smart pointers is the best option for your use case.
