### ISSUE TITLE
[Bug]: Unable to properly decompress and preview the format of tar.bz2

### ISSUE THREAD

**Issue by psvajaz** [rikyoz/bit7z#159]
### bit7z version

4.0.x RC

### Compilation options

BIT7Z_AUTO_FORMAT, BIT7Z_USE_NATIVE_STRING

### 7-zip version

v22.01

### 7-zip shared library used

7z.dll / 7z.so

### Compilers

MSVC

### Compiler versions

MSVC2017

### Architecture

x86_64

### Operating system

Windows

### Operating system versions

Windows 11, Windows10

### Bug description

Unable to properly decompress and preview the format of tar.bz2.
7zFM show file type is bzip2

TestFile: Because GitHub does not support uploading files in bz2 format, I will compress the test files using zip, and you can decompress them for testing
[TestFile.zip](https://github.com/rikyoz/bit7z/files/12178783/TestFile.zip)

7zFm and Winrar preview window:
![image](https://github.com/rikyoz/bit7z/assets/88539/6b25bc04-6333-43c0-b200-36f1ec36a112)

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
What problems are you having specifically?

Please consider the following details:
- The bzip2 format doesn't store any metadata about the compressed file, not even its name or attributes!
  - For this reason, the 7-zip DLLs, and hence bit7z, don't provide such information when previewing the content of a bz2 archive.
  - The 7-zip GUI avoids this by simply displaying the archive name without the `bz2` extension as the compressed file's name.
  - I'm studying whether to implement a workaround for this in the stable v4.0 so that it should behave like the 7-zip GUI.
- Bit7z doesn't currently support directly extracting the files inside the compressed tar.
  - You need first to extract the outer bz2 archive, obtaining the uncompressed tar; then, you need to extract the tar archive.
  - To avoid extracting the bz2 to the filesystem, you might extract it to a memory buffer and then extract this latter (i.e., the tar archive) to the filesystem.
  - I'll work on implementing recursive extraction of such archives, possibly for the future v4.1.

I did a quick test with your archive and had no particular issues while previewing or extracting it (provided what I wrote above).

**Comment by psvajaz** [comment]
OK, thank you. First, I'll test whether the bz2 file can be directly unzipped to the content, and then call the BitArchiveReader method to preview
