### ISSUE TITLE
[Feature Request]: Link static 7z lib

### ISSUE THREAD

**Issue by hcaihao** [rikyoz/bit7z#216]
### Feature description

Can bit7z link static 7z lib, I want build exe only application.

### Additional context

MT build with static 7z lib.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
Bit7z doesn't currently support static linking of 7-Zip.
I will definitely try to support it, but it will require many changes to both the public API and the internals of the library, so it probably won't come soon (maybe in a v5).

Also, I'm not a lawyer, but as far as I know, statically linking 7-Zip has some licensing implications for the end application.
Specifically, 7-Zip is licensed under the GNU LGPL, so if you statically link its source to your application, the latter must also be licensed under the GNU GPL/LGPL due to the virality of (L)GPL licences.
This does not apply to programs that currently use bit7z, as they don't use any code from 7-Zip (except for its public interfaces) and will dynamically use the 7-Zip DLLs.
