### ISSUE TITLE
[Feature Request]: BitOutputArchive::addFiles( const tstring& in_dir... should take options.only_files from an argument instead of 'false'

### ISSUE THREAD

**Issue by dhananjay-gune** [rikyoz/bit7z#226]
### Feature description

I observe that the 7z file created by using `BitOutputArchive::addFiles( const tstring& in_dir...` api, only captures the _files_ under the `in_dir`. It does not capture the sub-dirs in the `in_dir` for e.g. if the `in_dir` were to have the below structure:
`in_dir\FileA.txt`  
`in_dir\subDir`  
`in_dir\subDir\FileB.txt`  

when I call `BitArchiveReader.items()`, it reports only 2 items - `FileA.txt` and `FileB.txt` it does not report the `subDir`. 

This is because the `options.files_only` is hardcoded to `true`. When changed via debugger to `false`, the reader reports the `subDir` as well.

![image](https://github.com/user-attachments/assets/861bb71d-7b92-4527-a82b-b041cd951b41)

Would it be possible to take it from an argument?

I tried setting `mArchiveCreator.retainDirectories()` but it did not have any effect.

Env: Win10. 

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!

> Would it be possible to take it from an argument?

The problem I have with this change is that it would make the name of the method `addFiles` a bit ambiguous. By design, the method only adds files, not folders, hence the hardcoded value of `only_files`. If the method took an argument for this option, it would not just add files, contrary to what its name implies.

But I think the library should make it possible to do something like what you want, so I'm thinking the best way would be to add a method like `addDirectoryContent` (or just an overload of `addItems`) that adds everything it finds inside a directory.

There is already `addDirectory`, but it keeps the indexed directory as the root of the files added to the archive, so I think adding a new method is the best way to achieve this.

> when I call BitArchiveReader.items(), it reports only 2 items - FileA.txt and FileB.txt it does not report the subDir.

Just to be sure: after an `addFiles` call, the output archive should contain two items: `FileA.txt` and `subDir\FileB.txt` (not just `FileB.txt`), i.e., the metadata of the `subDir` folder is not stored in the archive, but the `FileB.txt` should have the `subDir\` in its path.

Anyway, I'll add the new method to the library, possibly in the upcoming v4.0.8 of the library.

Thanks for pointing this out!

**Comment by dhananjay-gune** [comment]
Thank you very much for a prompt reply, explanation, and the solution.  
I'll integrate the new version when ready.  

I just wanted to let you know that your library is very good and the work you are doing is really making a difference in the world.

**Comment by rikyoz** [comment]
> Thank you very much for a prompt reply, explanation, and the solution.

You're welcome!

I just pushed a [commit](https://github.com/rikyoz/bit7z/commit/eeffaae13544120bdb064a71cca4fe58816438d2) to the `hotfix/v4.0.8` branch that adds the `addDirectoryContents` method to `BitOutputArchive`.

> I just wanted to let you know that your library is very good and the work you are doing is really making a difference in the world.

Thank you for your kind words and support! I'm glad to hear that this library is making a positive impact. Feel free to reach out if you have any further questions or issues.

**Comment by dhananjay-gune** [comment]
Thanks! I'll take the 4.0.8 after you release it.

**Comment by dhananjay-gune** [comment]
Shouldn't the same functionality be extended to the classes that _wrap_ the `BitOutputArchive`? i.e. those who implement `BitAbstractArchiveCreator` e.g. `BitFileCompressor`, `BitArchiveWriter`, ... , Or perhaps in the `BitAbstractArchiveCreator` class itself... I don't know....

In other words, if I only wanted to use the `BitOutputArchive.addDirectoryContents()` or some other methods of the class, which _archive creator_ should I inject?

**Comment by rikyoz** [comment]
> Shouldn't the same functionality be extended to the classes that wrap the BitOutputArchive? i.e. those who implement BitAbstractArchiveCreator e.g. BitFileCompressor, BitArchiveWriter, ... , Or perhaps in the BitAbstractArchiveCreator class itself... I don't know....

This is automatically done for `BitArchiveWriter`, as it extends `BitOutputArchive` (and `BitAbstractArchiveCreator`), and for `BitArchiveEditor`, which extends `BitArchiveWriter`.

`BitFileCompressor` is different though, as it internally _uses_ `BitOutputArchive`, instead of inheriting from it. I think it makes sense to add a function like `compressDirectoryContents()`, given it already provides a `compressDirectory()` method. I'll add it asap to the v4.0.8 branch.

> In other words, if I only wanted to use the `BitOutputArchive.addDirectoryContents()` or some other methods of the class, which _archive creator_ should I inject?

`BitFileCompressor` is meant to be used when you want to create multiple archives using the same settings and callbacks. In all other cases, e.g., creating only one archive, or creating different archives with different settings, `BitArchiveWriter` is usually a better choice.
