### ISSUE TITLE
Unable to create archive in .bz2 or .xz formats

### ISSUE THREAD

**Issue by dhananjay-gune** [rikyoz/bit7z#234]
I am using `BitFileCompressor` to create archives from a folder or 'file map'.  

```C++
BitFileCompressor compressor(lib, archiveFormat);
compressor.compress(fileMap, archivePath); // fileMap contains filePath and entryName
```
If the archiveFormat is `bit7z::BitFormat::BZip2` and `bit7z::BitFormat::Xz`, it throws an exception:  
_"Cannot compress multiple files: Unsupported operation."_

It works fine for SevenZip, Zip, GZip.

Any clues?

**Comment by rikyoz** [comment]
Hi!
> If the archiveFormat is bit7z::BitFormat::BZip2 and bit7z::BitFormat::Xz, it throws an exception:
"Cannot compress multiple files: Unsupported operation."

This is the expected behavior, as the `BZip2` and `Xz` formats support compressing only one file, so you cannot compress folders or list/maps of more than one files.

> It works fine for SevenZip, Zip, GZip.

The fact that it works for `GZip` is the most strange thing here, as also this format allows only compressing one file, not more, and the same check is performed.

**Comment by dhananjay-gune** [comment]
sorry - it was a typo! `GZip` is indeed exhibits the same behaviour as `BZip2` and `XZ`

**Comment by rikyoz** [comment]
No problem!
