### ISSUE TITLE
Opening Tar file with Zip format does not fail

### ISSUE THREAD

**Issue by dhananjay-gune** [rikyoz/bit7z#235]
I am writing a negative test case for a function like `containsArchiveEntry()`.  
So I created a `.tar` file and trying to open it through `bit7z::BitFormat::Zip` .  
I am expecting it to fail, but it _partially_ succeeds 😮  i.e. it is able to iterate through the *some* items, _but not all_.  

I am trying to look for  `Sub Folder 2\Sub File 2.2.txt` 👈 

<pre>
D:\MyFolder
|   Root File 2.txt
|   Root File 3.7z
|   RootFile1.txt
|
+---Sub Folder 2
|       Sub File 2.2.txt 👈 
|       Sub File 2.3.tar
|       SubFile2.1.txt
|
\---SubFolder1
        Sub File 1.2.txt
        SubFile1.1.txt
        SubFile1.3.zip
</pre>

The `BitArchiveReader` reports only these entries, but at the _root level_.  
It does not report any other entries.  
```
Sub File 1.2.txt
SubFile1.1.txt
```

here is my code:
```C++
const BitInFormat & archiveFormat = GetInputArchiveFormat();
Bit7zLibrary lib(this->m_7ZipDllPath);
BitArchiveReader reader( lib, archivePath, archiveFormat); // 👉 here the archive file is .tar, but the archiveFormat is .Zip
for each (auto entry in reader)
{
    auto itemPath = entry.path();
    auto compareResult = lstrcmpi(itemPath.c_str(), archiveEntry.c_str()); // case insensitive comparison
    bool isEqual =  compareResult == 0;
    if (isEqual)
    {
        return OpResult(true);
    }
}
return OpResult(false);
```

The tar file shows all the entries:
![2024-08-19 11_55_01-](https://github.com/user-attachments/assets/d47206c6-04c2-4d3f-af81-f81e2e8ebff8)

I have embedded the tar file inside a zip file here:
[Test_ContainsArchiveEntryContainingTarFile.zip](https://github.com/user-attachments/files/16656528/Test_ContainsArchiveEntryContainingTarFile.zip)

I am expecting it to throw an exception when the formats don't match.  
Any clues?

**Comment by rikyoz** [comment]
Hi!

> The `BitArchiveReader` reports only these entries, but at the _root level_. It does not report any other entries.
> 
> ```
> Sub File 1.2.txt
> SubFile1.1.txt
> ```

In reality, what happens is something else: you're actually reading the content of the only Zip file inside the Tar archive, `SubFile1.3.zip`.
Coincidentally, the content of this Zip archive is the same of the `SubFolder1` (without the Zip file itself, of course):

![image](https://github.com/user-attachments/assets/0d705857-57c1-4b4c-ad55-086d985ce599)

But this is only a coincidence.

Basically, since you requested to read a Zip archive, 7-Zip seeks through the Tar archive in search of the start of the Zip archive (i.e., the magic number `PK...`).
Since the Tar archive is not compressed, 7-Zip can find it, and starts reading the Zip archive within the Tar.
In other cases where the inner archive is within a _compressed_ archive, the reader should throw an exception, as expected.

> I am expecting it to throw an exception when the formats don't match.

The fact that it doesn't throw in this particular case is mainly due to backwards compatibility with previous versions of bit7z.
Making it throw would be a breaking change in the library's behavior, so I'm evaluating whether and how to include this change in a future minor/patch version of bit7z.

**Comment by dhananjay-gune** [comment]
Thanks for this detail analysis.  
It would be really nice to have some tweak 🙏 e.g. via preprocessor macro or a bool in class - you know best.  :-)

**Comment by dhananjay-gune** [comment]
Thanks - I will take it in the coming weeks and give you feedback!
