### ISSUE TITLE
Compile option

### ISSUE THREAD

**Issue by octalflow** [rikyoz/bit7z#249]
### Feature description

In windows,
cmake ../ -DCMAKE_BUILD_TYPE=Release -DBIT7Z_STATIC_RUNTIME=ON -DBIT7Z_AUTO_FORMAT=ON -DBIT7Z_USE_NATIVE_STRING=ON

cmake --build . -j --config Release

But msvc 2022 could not link.

How to specify BIT7Z_AUTO_FORMAT / BIT7Z_USE_NATIVE_STRING ?

thanks in advance.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by octalflow** [comment]
BitArchiveReader.
Can I use chunk of memory(malloced memory) ?

**Comment by rikyoz** [comment]
Hi!

> In windows, cmake ../ -DCMAKE_BUILD_TYPE=Release -DBIT7Z_STATIC_RUNTIME=ON -DBIT7Z_AUTO_FORMAT=ON -DBIT7Z_USE_NATIVE_STRING=ON
> 
> cmake --build . -j --config Release
> 
> But msvc 2022 could not link.
>
> How to specify BIT7Z_AUTO_FORMAT / BIT7Z_USE_NATIVE_STRING ?

Do you mean MSVC could not link to produce the static library, or it could not link the static library to your project's executable?

In the latter case, please check that you're building your project using the `/MT` flag, as  you're using `-DBIT7Z_STATIC_RUNTIME=ON`. If you're using the `/MD` flag in your project, you must not enable the `BIT7Z_STATIC_RUNTIME` option (which is `OFF` by default).

Also, if you're not directly including the library in your project via CMake, but you're simply linking the `bit7z.lib` produced by the `cmake --build ...` command, you also need to define the same preprocessor options you used to build bit7z.
For example, in Visual Studio, you should do this:

![image](https://github.com/user-attachments/assets/f04023b5-78ca-4ef7-b81b-f7004357a7c3)

This is needed because the bit7z headers use these preprocessor flags to change the API they provide to your program, and if you don't set them, the headers will provide a different API than the one provided by the `bit7z.lib` library, hence the linker errors.

> BitArchiveReader.
> Can I use chunk of memory(malloced memory) ?

There is a specialization of the [`extractTo`](https://github.com/rikyoz/bit7z/wiki/BitArchiveReader#void-extractto-byte_t-buffer-stdsize_t-size-uint32_t-index--0--const) method that takes a pointer to a pre-allocated buffer, the size of the buffer, and the index of the file to be extracted.

**Comment by octalflow** [comment]
thank you.
