### ISSUE TITLE
Compile error on Windows

### ISSUE THREAD

**Issue by octalflow** [rikyoz/bit7z#251]
### Feature description

auto read_symlink_as_string( const fs::path& symlinkPath ) noexcept -> std::string {
    std::error_code error;
    return fs::read_symlink( symlinkPath, error ).u8string();     <---- C2440 error
}

Can I use it ?
return fs::read_symlink( symlinkPath, error ).string();  

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
> auto read_symlink_as_string( const fs::path& symlinkPath ) noexcept -> std::string { std::error_code error; return fs::read_symlink( symlinkPath, error ).u8string(); <---- C2440 error }

The error usually happens when you try to build bit7z using the C++20 standard.
At the moment, bit7z can only be built using the C++17 standard (but it can be used in C++20 programs without issues).

> Can I use it ? return fs::read_symlink( symlinkPath, error ).string();

The problem with the `string()` method on Windows is that it doesn't guarantee that the string is UTF-8. By default it uses the system codepage encoding, which (unfortunately) is often not UTF-8. This encoding may not be able to represent all the characters in the path stored in the symbolic link, so it may cause some problems.
This is the reason for using `u8string()`, which however had a breaking change from C++17 (where it returned a UTF-8 encoded `std::string`) to C++20 (where it returns a `std::u8string`), hence your error.
As I said, I suggest you compile bit7z with C++17, as it can still be used in C++20 programs (or at least I have never encountered a problem mixing standards in my test programs using bit7z).

Anyway, I plan to fix this and make bit7z build using C++20, but probably in the next v4.1-beta, not soon.

**Comment by octalflow** [comment]
Thanks!!!
