### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by octalflow** [rikyoz/bit7z#254]
### Feature description

arc = new BitArchiveReader(bit7z_lib, file_buffer);  // file_buffer(local variable) is buffer_t

arc created successfully.
later I move the variable file_buffer like this.

some_global = file_buffer; // move local variable to GLOBAL

but when I access some_global(global), It crashed(vs2022 write access violation).

Why ?

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
One problem I can see with your code is that after moving `file_buffer` to `some_global`, the `arc` instance still holds a reference to the local buffer, not the global one; this buffer doesn't contain the archive anymore, so `BitArchiveReader` will probably have problems trying to read it.

But the main problem is that `arc`, being dynamically allocated, is likely to outlive the local `file_buffer`: if the latter goes out of scope, the reader will have an invalid reference/pointer to a non-existent buffer. As soon as the reader tries to read from the buffer, it is likely to crash due to an invalid memory read in the best case.

In general, I suggest not to use dynamic memory allocation for bit7z's objects unless it is really necessary.

As for the write violation on `some_global`, I'm not sure what the cause is, and it's difficult to find out without a fully reproducible example, but I would guess it's due to some other invalid memory access problem.

**Comment by octalflow** [comment]
thank you.
