### ISSUE TITLE
[Bug]: The number of files read is incorrect

### ISSUE THREAD

**Issue by ywapple** [rikyoz/bit7z#266]
### bit7z version

4.0.x

### Compilation options

BIT7Z_7ZIP_VERSION, BIT7Z_AUTO_FORMAT

### 7-zip version

v23.01

### 7-zip shared library used

7z.dll / 7z.so

### Compilers

MSVC

### Compiler versions

vs2022

### Architecture

x86_64

### Operating system

Windows

### Operating system versions

win11

### Bug description

Bit7zLibrary lib;
BitArchiveReader arc{ lib, zipFile, BitFormat::Auto, strOpenPwd };
([20241219105522317.zip](https://github.com/user-attachments/files/18193209/20241219105522317.zip))

-----------------------------
Only 1 file was read, but there are actually 8 files. Using the built-in compression of Windows 11 system, you can see 8 files and decompress them normally

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!

> Only 1 file was read, but there are actually 8 files. Using the built-in compression of Windows 11 system, you can see 8 files and decompress them normally

Strange! I think it's either a problem with the zip file or with 7-Zip rather than bit7z, because even the 7-Zip GUI only shows one file inside the archive:

![Screenshot 2024-12-19 084920](https://github.com/user-attachments/assets/4c2e01f7-8d5e-4e04-a1e4-3f1450111549)

Testing the archive fails, so the zip file appears to be corrupt:

![Screenshot 2024-12-19 085011](https://github.com/user-attachments/assets/4750e4e0-c13d-4728-a496-9eff1f607019)

As a further check, I opened the archive with WinRAR, and while it shows several files inside, it also confirms that the archive seems to be corrupted:
![image](https://github.com/user-attachments/assets/3385ff1d-c98e-40cf-90ce-4e77634e961f)

**Comment by levicki** [comment]
@rikyoz This seems to be a bug in 7-Zip code. This ZIP file can be extracted without errors by Total Commander. I bet WinZIP can also handle it without issues.

**Comment by rikyoz** [comment]
> This seems to be a bug in 7-Zip code. This ZIP file can be extracted without errors by Total Commander. I bet WinZIP can also handle it without issues.

I initially thought that too, but I'm not sure.
I just tested the archive with WinZIP, and it gave some errors:

![image](https://github.com/user-attachments/assets/5ead56c2-b90b-43b1-9bbe-1ef6482a1d0c)

It's strange that Windows 11's built-in ZIP reader and Total Commander don't complain, while 7-Zip, WinRAR and WinZIP do.

**Comment by levicki** [comment]
> It's strange that Windows 11's built-in ZIP reader and Total Commander don't complain, while 7-Zip, WinRAR and WinZIP do.

Well to me it seems like a deliberately crafted archive where main archive data differs from individual file data -- your message says 4GB compressed size which is impossible since there's not that much data in the archive and central directory says proper size.

If you ask me as a user I prefer the smart software which does the reasonable thing:

1. Doesn't choke on the first "corrupt" file and say "I can't work with this! It's not perfect!" but instead lets you extract as much as possible
2. Doesn't bother you with an otherwise pointless error message unless it actually can't successfully decompress a file

So for me yes, all tools that fail miserably to work as outlined above have a bug -- a bug of being extremely anally retentive and user unfriendly.

**Comment by rikyoz** [comment]
> > It's strange that Windows 11's built-in ZIP reader and Total Commander don't complain, while 7-Zip, WinRAR and WinZIP do.
> 
> Well to me it seems like a deliberately crafted archive where main archive data differs from individual file data -- your message says 4GB compressed size which is impossible since there's not that much data in the archive and central directory says proper size.

I've come to the same conclusion.

> If you ask me as a user I prefer the smart software which does the reasonable thing:
> 
> 1. Doesn't choke on the first "corrupt" file and say "I can't work with this! It's not perfect!" but instead lets you extract as much as possible
> 2. Doesn't bother you with an otherwise pointless error message unless it actually can't successfully decompress a file
> 
> So for me yes, all tools that fail miserably to work as outlined above have a bug -- a bug of being extremely anally retentive and user unfriendly.

Yeah, as far as I am concerned, I think these tools should at least provide a configuration option that allows you to decide whether you want to read the archive "pedantically" or allow some flexibility and extract as much as possible.

Anyway, I'm closing the issue, as there isn't much that bit7z can do in this case.
