### ISSUE TITLE
Problems with extracting multi-volume

### ISSUE THREAD

**Issue by chaseYLC** [rikyoz/bit7z#49]
**bug**

Fails to extract files created by applying mult-volume.

**Env**
- Windows 10
- x86
- msvc 2019
- bit7z : v3.1.2
- 7-zip : v16.04

**Details**

I set the volume size of 10mb
```
compressor.setVolumeSize(1024 * 1024 * 10);

```
Files smaller than the volume size were successfully extracted. ('myfile.001' file only ).
However, extract fails when multiple files are created. ('myfiles.001 ... myfiles.021')

Extraction by programming fails, but Extraction succeeds when an external 7z program is used. So I think compression is not a problem.

The code where the failure occurs is this:
```
IInArchive* BitInputArchive::openArchiveStream( const BitArchiveHandler& handler,
                                                const wstring& name,
                                                IInStream* in_stream ) {

    ... 

    // Trying to open the file with the detected format
    HRESULT res = in_archive->Open( in_stream, nullptr, open_callback );

    ...    

}

res is S_FALSE !!

```

**Comment by rikyoz** [comment]
Hi!
This issue is strange. I don't seem to have any problem with the extraction of multi-volume archives.
Just two questions:

+ What archive format do you use for the compression?
+ What archive format do you use when extracting the archive?

Please note that even though you used a format like `BitFormat::SevenZip` for compressing a multi-volume archive, you need to use the `BitFormat::Split` format for extracting it!

**Comment by chaseYLC** [comment]
Thank you. It was caused by not using "BitFormat::Split". I didn't know I had to get 1 archive using "BitFormat::Split" .

**Comment by rikyoz** [comment]
No problem! Yeah, I definitely need to better document this detail!
Thank you anyway for using bit7z!
