### ISSUE TITLE
[Bug]: progress_size is incorrect 

### ISSUE THREAD

**Issue by ibaoyun** [rikyoz/bit7z#94]
### bit7z version

3.1.x

### 7-zip version

v21.07

### 7-zip DLL used

7z.dll

### MSVC version

2022

### Architecture

x86_64

### Which version of Windows are you using?

Windows 11

### Bug description

When I unpack the big ISO file with bit7z, the value obtained by setprogresscallback is always less than the value obtained by settotalcallback, so I can't judge whether it is completed successfully.

### Steps to reproduce

std::string ext = getFileExtName(fileName);
		bit7z::Bit7zLibrary lib(L"7z.dll");
		std::shared_ptr<bit7z::BitExtractor> extractor = nullptr;
		uint64_t total = 0;
		std::string currentItemName = "";
		if (ext == "iso") {
			extractor = std::make_shared<bit7z::BitExtractor>(lib, bit7z::BitFormat::Udf);
		}
		else {
			if (failed != nullptr) {
				failed(u8"不支持的文件格式");
			}
			return;
		}
		extractor->setFileCallback([&](std::wstring name) {
				if (fileCallback != nullptr) {
					DECODE_ON_FILE p;
					p.name = wstr2str(name);
					currentItemName = p.name;
					fileCallback(p);
				}
			});
		extractor->setProgressCallback([&](uint64_t progress_size) {
				if (progressCallback != nullptr) {
					DECODE_PROGRESS p;
					p.total = total;
					int percent = static_cast<int>((100.0 * progress_size) / total);
					p.percent = percent;
					p.current = progress_size;
					progressCallback(p);
					if (finished != nullptr) {
						if (percent == 100) {
							finished();//Never implement
						}
					}
				}
			});
		extractor->setTotalCallback([&](uint64_t total_size) {
				total = total_size;
			});

		std::string savePath = trimFileExt(fileName) ;
		if (!isDirExist(savePath)) {
			makeDir(savePath);
		}
		
		extractor->extract(str2wstr(fileName), str2wstr(savePath));	

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!

> When I unpack the big ISO file with bit7z, the value obtained by setprogresscallback is always less than the value obtained by settotalcallback, so I can't judge whether it is completed successfully.

I did some tests, and I noticed the same issue. It seems to be a problem that was introduced by 7-zip v21.07 and later. I tested with earlier versions (e.g., the v21.06), and it doesn't have the same problem.
I'll investigate whether the actual bug is on bit7z usage of newer versions of 7-zip or it's a bug of these latter.

**Comment by rikyoz** [comment]
Hi!
I did some further checking, and I came to a conclusion that, unfortunately, this is issue is not due to a bug in bit7z but instead to one in 7-zip.
bit7z calls the progress callback when 7-zip itself reports an update to the total processed size; the library doesn't do much more, so I suspect that it's 7-zip that doesn't inform bit7z about the last bytes extracted.
Also, I checked with the 7-zip GUI, and at least in my case, it had the same issue with the same ISO file, leading me to think further it's a 7-zip issue.
