### ISSUE TITLE
How can hide the compressed file[Feature Request]: 

### ISSUE THREAD

**Issue by kak13amaplus** [rikyoz/bit7z#98]
### Feature description

I didn't find the API that compresses hidden files

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
Could you be more specific? 
Are you having any issues while compressing hidden files?
I did some quick tests and had no problems with hidden files.

**Comment by kak13amaplus** [comment]
I don't know which API can be used to hide the compressed files in the compressed package.

In addition, 

void compressFiles( const wstring& in_dir,
                 const wstring& out_archive,
                 bool recursive = true,
                 const wstring& filter = L"*.*" ) const;
when “in_dir” contains a file with no suffix name, the file will not be compressed.

**Comment by rikyoz** [comment]
> Thank you for your reply！

No worries! 

> I don't know which API can be used to hide the compressed files in the compressed package.

Uhm, I'm not quite sure I understand:
- If you want to set the hidden file attribute while or after compressing files, this is not possible with bit7z (at least for now).
- If you want to hide the compressed files so they will not be visible even when opening the archive with the `7-zip` GUI, I don't know if this is even possible. If this is what you want, do you have any examples of how to use the `7z.exe` tool to achieve it? In any case, there's no such API in bit7z, unfortunately.

> In addition,
> 
> void compressFiles( const wstring& in_dir, const wstring& out_archive, bool recursive = true, const wstring& filter = L"\*.\*" ) const; when “in_dir” contains a file with no suffix name, the file will not be compressed.

This is a limitation of the current bit7z version that is not easy to overcome since it would require too many changes, and now I'm more focused on the next major version. 
In practice, the `compressFiles` method works only for files with an extension (as you can see from the default wildcard filter).
I will definitely work on fixing this incorrect behavior in the next major version.
